# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Func_SecondWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import os
import sqlite3

refresh=0

conex=sqlite3.connect('database.db')
c = conex.cursor()
avisos=0


class Ui_Func_SecondWindow(object):
    def setupUi(self, Func_SecondWindow):
        global avisos
        Func_SecondWindow.setObjectName("Func_SecondWindow")
        Func_SecondWindow.resize(734, 220)
        ######################################Limitar  dimensões
        Func_SecondWindow.setMaximumWidth(734)
        Func_SecondWindow.setMinimumWidth(734)
        Func_SecondWindow.setMaximumHeight(220)
        Func_SecondWindow.setMinimumHeight(220)
        #######################################
        Func_SecondWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(30,30,46, 255), stop:1 rgba(45, 45, 65));")
        self.centralwidget = QtWidgets.QWidget(Func_SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.but_FuncSec_delete = QtWidgets.QPushButton(self.centralwidget)
        self.but_FuncSec_delete.setGeometry(QtCore.QRect(320, 170, 81, 31))
        self.but_FuncSec_delete.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color: rgb(212, 0, 0);\n"
"font: 14pt \"Segoe UI\";")
        self.but_FuncSec_delete.setObjectName("but_FuncSec_delete")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(280, 140, 171, 21))
        self.comboBox.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.func_entry1 = QtWidgets.QTextEdit(self.centralwidget)
        self.func_entry1.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.func_entry1.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"font: 11pt \"Segoe UI\";")
        self.func_entry1.setObjectName("func_entry1")
        self.func_entry2 = QtWidgets.QTextEdit(self.centralwidget)
        self.func_entry2.setGeometry(QtCore.QRect(160, 40, 131, 31))
        self.func_entry2.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"font: 11pt \"Segoe UI\";")
        self.func_entry2.setObjectName("func_entry2")
        self.func_entry3 = QtWidgets.QTextEdit(self.centralwidget)
        self.func_entry3.setGeometry(QtCore.QRect(300, 40, 131, 31))
        self.func_entry3.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"font: 11pt \"Segoe UI\";")
        self.func_entry3.setObjectName("func_entry3")
        self.func_entry4 = QtWidgets.QTextEdit(self.centralwidget)
        self.func_entry4.setGeometry(QtCore.QRect(440, 40, 131, 31))
        self.func_entry4.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"font: 11pt \"Segoe UI\";")
        self.func_entry4.setObjectName("func_entry4")
        self.func_entry5 = QtWidgets.QTextEdit(self.centralwidget)
        self.func_entry5.setGeometry(QtCore.QRect(580, 40, 131, 31))
        self.func_entry5.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"font: 11pt \"Segoe UI\";")
        self.func_entry5.setObjectName("func_entry5")
        self.but_FuncSec_create = QtWidgets.QPushButton(self.centralwidget)
        self.but_FuncSec_create.setGeometry(QtCore.QRect(320, 90, 81, 31))
        self.but_FuncSec_create.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"font: 14pt \"Segoe UI\";\n"
"color: rgb(16, 117, 0)")
        self.but_FuncSec_create.setObjectName("but_FuncSec_create")
        self.func_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.func_label_1.setGeometry(QtCore.QRect(20, 20, 721, 16))
        self.func_label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 12pt \"Segoe UI\";")
        self.func_label_1.setObjectName("func_label_1")
        Func_SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Func_SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 22))
        self.menubar.setObjectName("menubar")
        Func_SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Func_SecondWindow)
        self.statusbar.setObjectName("statusbar")
        Func_SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Func_SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(Func_SecondWindow)

        self.but_FuncSec_create.clicked.connect(self.Add_Func)
        self.but_FuncSec_delete.clicked.connect(self.Del_Func)
        #
        self.comboBox.clear()
        #################REFRESH COMBOBOX
        c.execute("SELECT * from 'Funcionarios'")
        numRows=len(c.fetchall())
        self.comboBox.clear()
        c.execute("SELECT * from 'Funcionarios'")
        for i in range(1,numRows+1):
            self.comboBox.addItem("{}".format(str(i)))
        #


        Func_SecondWindow.setWindowIcon(QtGui.QIcon('logo.png'))



    def retranslateUi(self, Func_SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        Func_SecondWindow.setWindowTitle(_translate("Func_SecondWindow", "Manutenção de funcionários"))
        self.but_FuncSec_delete.setText(_translate("Func_SecondWindow", "Deletar"))
        self.but_FuncSec_create.setText(_translate("Func_SecondWindow", "Adicionar"))
        self.func_label_1.setText(_translate("Func_SecondWindow", "Nome                        Idade                        Endereço                 Salário                   Data de contratação"))

    def Add_Func(self):
        DataInsert=['','','','','']
        #1
        if str(self.func_entry1.toPlainText())!='':
            DataInsert[0]=str(self.func_entry1.toPlainText())
        #2
        if str(self.func_entry2.toPlainText())!='':
            DataInsert[1]=str(self.func_entry2.toPlainText())
        #3
        if str(self.func_entry3.toPlainText())!='':
            DataInsert[2]=str(self.func_entry3.toPlainText())
        #4
        if str(self.func_entry4.toPlainText())!='':
            DataInsert[3]=str(self.func_entry4.toPlainText())
        #5
        if str(self.func_entry5.toPlainText())!='':
            DataInsert[4]=str(self.func_entry5.toPlainText())
        DataInsert2=str(DataInsert).replace('[','(')
        DataInsert2=DataInsert2.replace(']',')')
        c.execute("INSERT INTO '{}' VALUES {}".format('Funcionarios', DataInsert2))
        conex.commit()
        global avisos
        if avisos==0:
            self.msg = QMessageBox()
            self.msg.setWindowTitle('Tabela atualizada')
            self.msg.resize(200,200)
            self.msg.move(600,300)
            self.msg.setText('Atualize a tabela.')
            self.msg.setIcon(QMessageBox.Information)
            self.msg.setStandardButtons(QMessageBox.Ok)
            self.msg.show()
            avisos+=1
        #################REFRESH COMBOBOX
        c.execute("SELECT * from 'Funcionarios'")
        numRows=len(c.fetchall())
        self.comboBox.clear()
        for i in range(1,numRows+1):
            self.comboBox.addItem("{}".format(str(i)))
        ##
######
    def Del_Func(self):
        try:
            #
            NumDel=int(self.comboBox.currentText())
            c.execute("SELECT rowid, * from 'Funcionarios'")
            REAL_NumDel=((c.fetchall())[NumDel-1])[0]
            c.execute("SELECT rowid, * from '{}'".format('Funcionarios'))
            c.execute("DELETE from '{}' where rowid = {}".format('Funcionarios', str(REAL_NumDel)))
            conex.commit()
            #
            global avisos
            if avisos==0:
                self.msg = QMessageBox()
                self.msg.setWindowTitle('Tabela atualizada')
                self.msg.resize(200,200)
                self.msg.move(600,300)
                self.msg.setText('Atualize a tabela.')
                self.msg.setIcon(QMessageBox.Information)
                self.msg.setStandardButtons(QMessageBox.Ok)
                self.msg.show()
                avisos+=1
            #################REFRESH COMBOBOX
            c.execute("SELECT * from 'Funcionarios'")
            numRows=len(c.fetchall())
            self.comboBox.clear()
            for i in range(1,numRows+1):
                self.comboBox.addItem("{}".format(str(i)))
            ##
        except:
            pass
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Func_SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_Func_SecondWindow()
    ui.setupUi(Func_SecondWindow)
    Func_SecondWindow.show()
    sys.exit(app.exec_())
