# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proj_SecWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import sqlite3

global avisos
avisos=0



conex=sqlite3.connect('database.db')
c = conex.cursor()

class Ui_Proj_SecWindow(object):
    def setupUi(self, Proj_SecWindow):
        global avisos
        Proj_SecWindow.setObjectName("Proj_SecWindow")
        Proj_SecWindow.resize(382, 462)
        ######################################Limitar  dimensões
        Proj_SecWindow.setMaximumWidth(382)
        Proj_SecWindow.setMinimumWidth(382)
        Proj_SecWindow.setMaximumHeight(462)
        Proj_SecWindow.setMinimumHeight(462)
        #######################################
        Proj_SecWindow.setStyleSheet("background-color: rgb(30, 30, 46);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(30,30,46, 255), stop:1 rgba(40, 40, 55));")
        self.centralwidget = QtWidgets.QWidget(Proj_SecWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.But_CreateProj = QtWidgets.QPushButton(self.centralwidget)
        self.But_CreateProj.setGeometry(QtCore.QRect(50, 220, 281, 51))
        self.But_CreateProj.setStyleSheet("background-color: rgb(187, 181, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.But_CreateProj.setObjectName("But_CreateProj")
        self.But_ProjFinal = QtWidgets.QPushButton(self.centralwidget)
        self.But_ProjFinal.setGeometry(QtCore.QRect(50, 380, 281, 31))
        self.But_ProjFinal.setStyleSheet("background-color: rgb(224, 255, 234);\n"
"font: 10pt \"Segoe UI\";")
        self.But_ProjFinal.setObjectName("But_ProjFinal")
        self.But_ProjAband = QtWidgets.QPushButton(self.centralwidget)
        self.But_ProjAband.setGeometry(QtCore.QRect(50, 410, 281, 31))
        self.But_ProjAband.setStyleSheet("background-color: rgb(241, 227, 227);\n"
"font: 10pt \"Segoe UI\";")
        self.But_ProjAband.setObjectName("But_ProjAband")
        self.comboBox_Proj = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Proj.setGeometry(QtCore.QRect(50, 331, 281, 31))
        self.comboBox_Proj.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.comboBox_Proj.setObjectName("comboBox_Proj")
        self.proj_entryId = QtWidgets.QTextEdit(self.centralwidget)
        self.proj_entryId.setGeometry(QtCore.QRect(30, 20, 111, 31))
        self.proj_entryId.setStyleSheet("color: rgb(255, 255, 255);")
        self.proj_entryId.setOverwriteMode(False)
        self.proj_entryId.setObjectName("proj_entryId")
        self.proj_entryNome = QtWidgets.QTextEdit(self.centralwidget)
        self.proj_entryNome.setGeometry(QtCore.QRect(150, 20, 201, 31))
        self.proj_entryNome.setStyleSheet("color: rgb(255, 255, 255);")
        self.proj_entryNome.setObjectName("proj_entryNome")
        self.proj_entryFunc = QtWidgets.QTextEdit(self.centralwidget)
        self.proj_entryFunc.setGeometry(QtCore.QRect(30, 70, 321, 31))
        self.proj_entryFunc.setStyleSheet("color: rgb(255, 255, 255);")
        self.proj_entryFunc.setObjectName("proj_entryFunc")
        self.proj_entryCliente = QtWidgets.QTextEdit(self.centralwidget)
        self.proj_entryCliente.setGeometry(QtCore.QRect(30, 120, 321, 31))
        self.proj_entryCliente.setStyleSheet("color: rgb(255, 255, 255);")
        self.proj_entryCliente.setObjectName("proj_entryCliente")
        self.proj_entryContatoCliente = QtWidgets.QTextEdit(self.centralwidget)
        self.proj_entryContatoCliente.setGeometry(QtCore.QRect(30, 170, 321, 31))
        self.proj_entryContatoCliente.setStyleSheet("color: rgb(255, 255, 255);")
        self.proj_entryContatoCliente.setObjectName("proj_entryContatoCliente")
        Proj_SecWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Proj_SecWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 22))
        self.menubar.setObjectName("menubar")
        Proj_SecWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Proj_SecWindow)
        self.statusbar.setObjectName("statusbar")
        Proj_SecWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Proj_SecWindow)
        QtCore.QMetaObject.connectSlotsByName(Proj_SecWindow)

        ####

        self.But_CreateProj.clicked.connect(self.Add_Proj)

        self.But_ProjAband.clicked.connect(self.Del_Proj)

        self.But_ProjFinal.clicked.connect(self.Del_Proj)
        
        ###########################REFRESH COMBOBOX_PROJ
        self.comboBox_Proj.clear()
        c.execute("SELECT * from 'Projetos'")
        numRows_Proj=len(c.fetchall())
        for i in range(1,numRows_Proj+1):
            self.comboBox_Proj.addItem("{}".format(str(i)))

        #######

        Proj_SecWindow.setWindowIcon(QtGui.QIcon('logo.png'))

        ########

    def retranslateUi(self, Proj_SecWindow):
        _translate = QtCore.QCoreApplication.translate
        Proj_SecWindow.setWindowTitle(_translate("Proj_SecWindow", "Manutenção de projetos"))
        self.But_CreateProj.setText(_translate("Proj_SecWindow", "Criar novo projeto"))
        self.But_ProjFinal.setText(_translate("Proj_SecWindow", "Projeto finalizado"))
        self.But_ProjAband.setText(_translate("Proj_SecWindow", "Projeto Abandonado"))
        self.proj_entryId.setHtml(_translate("Proj_SecWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.proj_entryId.setPlaceholderText(_translate("Proj_SecWindow", "Id"))
        self.proj_entryNome.setPlaceholderText(_translate("Proj_SecWindow", "Nome"))
        self.proj_entryFunc.setPlaceholderText(_translate("Proj_SecWindow", "Funcionários (Ex: Pedro, João, Joyce, Marcela.)"))
        self.proj_entryCliente.setPlaceholderText(_translate("Proj_SecWindow", "Cliente (Empresa/Indivíduo)"))
        self.proj_entryContatoCliente.setPlaceholderText(_translate("Proj_SecWindow", "Contato do cliente"))

    ####
    # proj_entryId , proj_entryNome , proj_entryFunc , proj_entryCliente, proj_entryContatoCliente 
    ###
    def Add_Proj(self):
        c.execute("SELECT * from 'Projetos'")
        DataInsert=['','','','','']
        #1
        if str(self.proj_entryId.toPlainText())!='':
            DataInsert[0]=str(self.proj_entryId.toPlainText())
        #2
        if str(self.proj_entryNome.toPlainText())!='':
            DataInsert[1]=str(self.proj_entryNome.toPlainText())
        #3
        if str(self.proj_entryFunc.toPlainText())!='':
            a=str(self.proj_entryFunc.toPlainText())
            b=a.find('\n')
            if b!=-1:
                a.replace('\n', ' ')
            DataInsert[2]=a
        #4
        if str(self.proj_entryCliente.toPlainText())!='':
            DataInsert[3]=str(self.proj_entryCliente.toPlainText())
        #5
        if str(self.proj_entryContatoCliente.toPlainText())!='':
            DataInsert[4]=str(self.proj_entryContatoCliente.toPlainText())
        DataInsert2=str(DataInsert).replace('[','(')
        DataInsert2=DataInsert2.replace(']',')')
        c.execute("INSERT INTO '{}' VALUES {}".format('Projetos', DataInsert2))
        conex.commit()
        global avisos
        if avisos==0:
            self.msg = QMessageBox()
            self.msg.setWindowTitle('Tabela atualizada')
            self.msg.resize(200,200)
            self.msg.move(600,300)
            self.msg.setText('Atualize a tabela.')
            self.msg.setIcon(QMessageBox.Information)
            self.msg.setStandardButtons(QMessageBox.Ok)
            self.msg.show()
            avisos+=1

        ###########################REFRESH COMBOBOX_PROJ
        c.execute("SELECT * from 'Projetos'")
        numRows_Proj=len(c.fetchall())
        self.comboBox_Proj.clear()
        for i in range(1,numRows_Proj+1):
            self.comboBox_Proj.addItem("{}".format(str(i)))
        ##

            
###########

    def Del_Proj(self):
        try:
            #
            NumDel=int(self.comboBox_Proj.currentText())
            c.execute("SELECT rowid, * from 'Projetos'")
            REAL_NumDel=((c.fetchall())[NumDel-1])[0]
            c.execute("SELECT rowid, * from '{}'".format('Projetos'))
            ###
            c.execute("SELECT rowid, * from '{}'".format('Projetos'))
            c.execute("DELETE from '{}' where rowid = {}".format('Projetos', str(REAL_NumDel)))
            #
            conex.commit()
            global avisos
            if avisos==0:
                self.msg = QMessageBox()
                self.msg.setWindowTitle('Tabela atualizada')
                self.msg.resize(200,200)
                self.msg.move(600,300)
                self.msg.setText('Atualize a tabela.')
                self.msg.setIcon(QMessageBox.Information)
                self.msg.setStandardButtons(QMessageBox.Ok)
                self.msg.show()
                avisos+=1

            ###########################REFRESH COMBOBOX_PROJ
            self.comboBox_Proj.clear()
            c.execute("SELECT * from 'Projetos'")
            numRows_Proj=len(c.fetchall())
            for i in range(1,numRows_Proj+1):
                self.comboBox_Proj.addItem("{}".format(str(i)))

            #######
        except:
            pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Proj_SecWindow = QtWidgets.QMainWindow()
    ui = Ui_Proj_SecWindow()
    ui.setupUi(Proj_SecWindow)
    Proj_SecWindow.show()
    sys.exit(app.exec_())
